name: Chrome
on: push
jobs:
    setup-cypress:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./my-cypress-project
        
        strategy:
            matrix:
                node-version: [22.3.0]
        
        env:
            MODE: "dev"
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                runTests: false
                build: |
                    npm install
                    npm run build
            
            - name: Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: build
            
    cypress-run:
        runs-on: ubuntu-22.04
        needs: setup-cypress
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Download the build folder
          uses: actions/download-artifact@v4
          with:
            name: build
            path: build

        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            start: npm start
            browser: chrome   
                